### PR TITLE
russian translation

### PR DESCRIPTION
**Pull request by XAOPT**

### CODE REVIEW

**Comment by 4kochi** [comment]
Thanks for your effort. There are some keys which are not translated yet. Could you also provide the translation for that keys?

**Comment by XAOPT** [comment]
Hi. Sure! Could you give me some kind of guest access to professional edition for best translation expirience?

**Comment by 4kochi** [comment]
Sure. Please use the contact form at our website (http://www.litixsoft.de/contact/) to send us your mail address. Then we can provide a version for you.

**Comment by XAOPT** [comment]
I think, I did my best )

**Comment by 4kochi** [comment]
Yes, looks great. We will add the translation in the next release. Thanks for your work.

**Pull request merged**
